name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      
      - name: Set up Pyhton
        id: setup-python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
        
      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      - name: List Directories
        run: ls -la

      - name: Run Tests
        run: pytest -v tests.py